### ISSUE TITLE
hover not working

### ISSUE THREAD

**Issue by ashee** [hackwaly/vscode-ocaml#1]
Even though type assist/autocomplete is working, I am not able to see the types when I hover my mouse. "Go to Definition" and "Peek Definition" does not work. 

My environment

```
Code
Version 1.2.0 (1.2.0)

$ uname -a
Darwin amitava.local 14.5.0 Darwin Kernel Version 14.5.0: Thu Apr 21 20:40:54 PDT 2016; root:xnu-2782.50.3~1/RELEASE_X86_64 x86_64

System Software Overview:

  System Version:   OS X 10.10.5 (14F1808)
  Kernel Version:   Darwin 14.5.0
```

**Comment by hackwaly** [comment]
@ashee Have you tried in a fresh new simple project? Could you please check the console of developer tools of VS Code. If there is something wrong.

EDIT: 
Which version of ocamlmerlin you used? I did not test versions other than 2.3.1.

**Comment by Fourchaux** [comment]
Same pb here  

```
Code
Version 1.2.0

Linux 4.1.15 x86_64 GNU/Linux
```

Unless I am mistaken but the OCaml mode is not automatically selected when a *.ml is used

**Comment by hackwaly** [comment]
@Fourchaux You're right. VS Code has a builtin F# support. *.ml is default associated to F#. You need config this.

```
"files.associations": {
    "*.ml": "ocaml"
}
```

**Comment by Fourchaux** [comment]
Already done, but thank you for the confirmation :)

**Comment by ashee** [comment]
I did change filetype to ocaml. Even though I see autocompletion, nothing else.

**Comment by hackwaly** [comment]
@ashee Does "hover" and "goto def" works for file local symbols? If symbols are defined in other files, They need be compiled first AFAIK. 

If your project structure is not flat. merlin should be configured accordingly. This might be useful.
https://github.com/the-lambda-church/merlin/wiki/project-configuration

**Comment by ashee** [comment]
No - nothing happens, either for local symbols or library functions such as Printf.printf

**Comment by hackwaly** [comment]
Hello @ashee .
Can you follow these instructions to find out the root of problem? I made a special git branch for you.

``` shell
git clone https://github.com/hackwaly/vscode-ocaml.git
cd vscode-ocaml
git checkout for_ashee
npm install
```
1. Use VS Code open the folder "vscode-ocaml". 
2. press F5 to debug the extension. This will open a new VS Code window that use the local version of the OCaml extension. 
3. Then use "File" menu to open an OCaml project folder. 
4. Hover on some identifier. Take a look the debugging window.

You will see something at debug output pane like this:

```
'/Applications/Visual Studio Code.app/Contents/MacOS/Electron' --debugBrkPluginHost=20976 --extensionDevelopmentPath=/Users/wenyuxiang/Sandbox/vscode-ocaml 
正在 /Users/wenyuxiang/Sandbox/vscode-ocaml 中加载开发扩展
[/Users/wenyuxiang/Sandbox/vscode-ocaml]: 使用 /Users/wenyuxiang/Sandbox/vscode-ocaml 覆盖扩展 /Users/wenyuxiang/.vscode/extensions/hackwaly.ocaml-0.2.4。
cmd to merlin: ["checkout","auto","/Users/wenyuxiang/Seafile/noodle/src/parsing/parsetree.ml"]
response from merlin: ["return",{"cursor":{"line":1,"col":0},"marker":false}]
cmd to merlin: ["seek","exact",{"line":1,"col":0}]
response from merlin: ["return",{"cursor":{"line":1,"col":0},"marker":false}]
cmd to merlin: ["tell","source-eof","open Num\n\ntype const =\n  | C_num of num\n  | C_string of string\n  | C_bool of bool\n\ntype exp =\n  | E_const of const\n  | E_call of exp * (string option * exp) list\n  | E_let of string option * exp * exp\n"]
response from merlin: ["return",{"cursor":{"line":12,"col":0},"marker":false}]
cmd to merlin: ["type","enclosing","at",{"line":11,"col":6}]
response from merlin: ["return",[{"start":{"line":8,"col":5},"end":{"line":13,"col":0},"type":"type exp =\n    E_const of const\n  | E_call of exp * (string option * exp) list\n  | E_let of string option * exp * exp","tail":"no"}]]
```

Paste it here.

**Comment by ashee** [comment]
When I launch the debugger, I get the following

![image](https://cloud.githubusercontent.com/assets/237894/15940221/080e8bc2-2e49-11e6-9ce6-2c06a7456731.png)

**Comment by ashee** [comment]
Ok - I had to build this extension.

```
$ npm i 
```

Switch to vscode and pres Cmd+Shift+B (build)  which generates the out directory. Now I am able to run the debugger. Will report back on the findings shortly.

**Comment by ashee** [comment]
cmd to merlin: ["checkout","auto","/Users/amitava/Projects/ocaml/srv/hello.ml"]
response from merlin: ["return",true]
cmd to merlin: ["seek","exact",{"line":1,"col":0}]
response from merlin: ["failure","invalid arguments"]
cmd to merlin: ["tell","source-eof","let () = \n  Printf.printf \"\n\" \"hello,world\"\n\n"]
response from merlin: ["failure","invalid arguments"]
cmd to merlin: ["type","enclosing","at",{"line":2,"col":11}]
response from merlin: ["return",[]]

**Comment by hackwaly** [comment]
Thank you for your report back!
It seems the merlin protocol mismatched. Are you using the dev channel of ocamlmerlin? Try `ocamlmerlin -version`. If it below 2.3.1, try upgrade it. 

```
opam update
opam upgrade merlin
```

I will add merlin protocol v2 support later. https://github.com/the-lambda-church/merlin/blob/master/doc/dev/PROTOCOL.md
For now this version of protocol is used. https://github.com/the-lambda-church/merlin/blob/v2.3.1/doc/dev/PROTOCOL.md

**Comment by ashee** [comment]
My version is much higher than v2.3.1

```
$ ocamlmerlin -version
The Merlin toolkit version git-87ea0e7998c04f16e4821676c27f19d3879dc2d1, for Ocaml 4.02.3
```

I should mention that it works perfectly with vim.

**Comment by hackwaly** [comment]
Hi @ashee. I have uploaded a new version v0.2.5 just fixed this. Update and enjoy!

**Comment by ashee** [comment]
Thanks - it worked.

**Comment by Fourchaux** [comment]
It works here too. Xièxiè.
