### ISSUE TITLE
Syntax highlighting broken for pattern matching

### ISSUE THREAD

**Issue by vogler** [hackwaly/vscode-ocaml#10]
There's a problem with syntax highlighting one-line pattern matches:
![image](https://cloud.githubusercontent.com/assets/493741/16301740/602077d6-3947-11e6-9034-418a19b0febd.png)

**Comment by hackwaly** [comment]
Hello, @vogler. Syntax highlighting is based on textmate grammar. I know there are many problems. Feel free to hack it and submit a pull request if you are familiar with it.

**Comment by vogler** [comment]
Ok, thanks, I'll have a look this weekend. Commenting out the first pattern also seems to be problematic:
![image](https://cloud.githubusercontent.com/assets/493741/16302806/756d0f54-394d-11e6-97c8-e21f1c11ee96.png)

**Comment by hackwaly** [comment]
I'm going to address this issue.

**Comment by hackwaly** [comment]
Fix in 0.4.22.

**Comment by vogler** [comment]
Comments are still problematic:
- single line: any comment before the first pattern
- multiple lines: comments that contain a `|` before the first pattern

![image](https://cloud.githubusercontent.com/assets/493741/16799648/31df83ca-48f2-11e6-964e-dae76277ef60.png)
