### ISSUE TITLE
Debugging does not work on a one-line file with no dependencies.

### ISSUE THREAD

**Issue by ewan-delanoy** [hackwaly/vscode-ocaml#103]
Details here : https://discuss.ocaml.org/t/simple-variable-assignment-triggers-out-of-bonds-exception-in-visual-studio-code/424

In this situation debugging outside VSCode works fine but debugging inside VSCode raises an exception

**Comment by hackwaly** [comment]
> In this situation debugging outside VSCode works fine but debugging inside VSCode raises an exception

I've tested ocamldebug doesn't work in that situation. How did you get it works?

<img width="502" alt="2017-06-17 9 30 38" src="https://user-images.githubusercontent.com/540298/27249099-0f2fc39a-5340-11e7-9182-b88181952d70.png">

**Comment by ewan-delanoy** [comment]
My mistake : when I tested outside VSCode, I forgot to set the breakpoint. 
When I test with the breakpoint outside VSCode I get the same result as you.
