### ISSUE TITLE
.ml indentation defaults to "Spaces: 2"

### ISSUE THREAD

**Issue by Simn** [hackwaly/vscode-ocaml#104]
OS: Windows 10
Visual Studio Code: 1.13.1
OCaml extension: 0.6.31

With the OCaml extension installed, all .ml files are indented as "Spaces: 2". If I uninstall or disable the extension, it's back to "Tab Size: 4" (my default). I think this occurs since the last Visual Studio Code update.

Any idea what might be causing this? I added this to my user settings:

```json
	"editor.tabSize": 4,
	"editor.detectIndentation": false
```

But that didn't change anything. This seem to affect all file extensions handled by this extension: .ml, .mli, .mly, .mll.

**Comment by hackwaly** [comment]
Since last version of vscode-ocaml, it contributes commonly accepted indent style  (tab-size 2 and soft-tabs enabled) as default editorconfig for ocaml language to vscode.

Add these to your user settings should change tabsize from 2 to 4.
```
      "[ocaml]": {
        "editor.tabSize": 4
      },
      "[ocamllex]": {
        "editor.tabSize": 4
      },
      "[menhir]": {
        "editor.tabSize": 4
      }
```

**Comment by Simn** [comment]
I see, thanks! I had to add `"editor.insertSpaces": false` as well to make it use tabs.

I'm surprised that this overrides the explicit user setting, but I suppose that's because the `[ocaml]` "selector" is more specific than the global setting. Feel free to close this if you want.
