### ISSUE TITLE
Please add env/envFile launch configuration attibutes

### ISSUE THREAD

**Issue by db4** [hackwaly/vscode-ocaml#105]
It can be done just the same way as in Node.js debugger:

- `env` - optional environment variables. This attribute expects environment variables as a list of string typed key/value pairs.
- `envFile` - optional path to a file containing environment variable definitions.

More details are there: https://code.visualstudio.com/docs/nodejs/nodejs-debugging

**Comment by hackwaly** [comment]
Done. https://github.com/hackwaly/vscode-ocaml/commit/80dd7e278c3d9aa1cba819ad97d19c9672e6926f
