### ISSUE TITLE
opam support

### ISSUE THREAD

**Issue by rgrinberg** [hackwaly/vscode-ocaml#108]
I noticed that the way vscode-ocaml currently resolves the paths of ocaml/merlin/ocp-indent is through a user setting. While that works, it's really inconvenient for opam users with multiple switches (a good chunk of users I assume). What would be really nice is the following:

* this plugin would let us select a "current" switch. A list of available switches is available using `$ opam switch list` for example.

* would then run merlin, ocp-indent, build commands by prefixing them with `$ opam exec --switch=<current-switch>`.

**Comment by hackwaly** [comment]
I'm not an opam user, and I don't understand all what you said. I've tried `opam exec --switch=4.04.0`,  but got these: 
```
  ~ opam exec --switch=4.04.0
opam: unknown command `exec'.
Usage: opam COMMAND ...
Try `opam --help' for more information.
```

**Comment by rgrinberg** [comment]
Try opam switch exec. I think opam exec is opam 2.0 only

**Comment by hackwaly** [comment]
Sorry, I still didn't get it.

**Comment by rgrinberg** [comment]
It's actually `$ opam config exec` for  older opams (1.2 and below).

If there's anything unclear, please feel free to ask as many questions as possible. I'd really like to get this done to make this plugin usable for opam users.
