### ISSUE TITLE
Recognize .ocamlinit as an OCaml file

### ISSUE THREAD

**Issue by vrotaru** [hackwaly/vscode-ocaml#11]
Currently out of the box, .ocamlinit is not supported as an OCaml file. This

``` json
    "files.associations": {
        "*.ml": "ocaml",
        ".ocamlinit": "ocaml"
    },
```

did the trick, but would be nice to have it out of the box.

P.S. Very nice extension. Thank you.

**Comment by hackwaly** [comment]
Nice to have! Are there any other filetypes should be considered as OCaml file?

**Comment by vrotaru** [comment]
I'm not aware of any other commonly used files besides .ocamlinit. 

Feel free to close the issue.
