### ISSUE TITLE
Switch to signature file even when it doesn't exist

### ISSUE THREAD

**Issue by Khady** [hackwaly/vscode-ocaml#111]
If I have a file `foo.ml` and I run the `ocaml.switch_mli_ml` command, it displays a notification `Signature file doesn't exist. New file has created for you.`. But it doesn't switch to the signature file. I have to run the command one more time. It would be nice to switch immediately to this newly created file.

**Comment by Khady** [comment]
Actually it does switch. But only after I close the notification. Maybe it's possible to make the notification not blocking so that the switch is done even if I don't close the notification.

**Comment by Khady** [comment]
Wow, I was working on a fix but you have been faster. Thanks!

**Comment by hackwaly** [comment]
@Khady, thank you!
