### ISSUE TITLE
Merlin is not reading the Core module although it's installed

### ISSUE THREAD

**Issue by sharno** [hackwaly/vscode-ocaml#117]
I'm new to OCaml and just did a fresh installation of OCaml, Core, Merlin and other stuff. Just started writing code in VSCode but it importing any module gives the same error as "Unbound module". This file compiles and runs fine though.

Also I made sure that merlin is in the path, checked it in process.env as well, and even replaced the merlin path with the absolute path of it. All giving the same error in the editor.

<img width="496" alt="screen shot 2017-09-28 at 11 33 56 pm" src="https://user-images.githubusercontent.com/601606/30999947-33e68216-a4a6-11e7-8b16-9f5299f4c417.png">

Is it a problem with Merlin or with the extension?

**Comment by hackwaly** [comment]
Write a `.merlin` file in your project. If you didn't know what's `.merlin`, seach it in merlin's wiki.

**Comment by sharno** [comment]
Thanks a lot. That wasn't obvious for me.
