### ISSUE TITLE
Feature: Add command to send whole file to REPL

### ISSUE THREAD

**Issue by dragomirtitian** [hackwaly/vscode-ocaml#121]
It would be very useful to be able to send the whole file to the REPL.

Use-case: When learning OCML it is simpler and faster to send the whole file to the REPL to evaluate the code. Right now the user would have to select the whole text in the file and use the "Send selection to REPL" command, a step that is very tedious if you need to do it often.

**Comment by hackwaly** [comment]
Released in 0.6.42
