### ISSUE TITLE
Data inspection via hovering?

### ISSUE THREAD

**Issue by db4** [hackwaly/vscode-ocaml#13]
Is hovering over variable's source expected to work in the debugger or this feature is not implemented yet?

**Comment by hackwaly** [comment]
This is not implemented due to the limitations of ocamldebug.

**Comment by db4** [comment]
Hmm, what limitations? It works in OCaIDE...

**Comment by hackwaly** [comment]
Curiously how OCaIDE done. We can't know the variable at source is related to which frame through ocamldebug.

**Comment by db4** [comment]
Why should you? You just evaluate an expression under cursor in the current frame via `print` command.

**Comment by hackwaly** [comment]
This feels weird if you used to use other excellent debuggers. 

Consider this code:

```
let x = "hello" in
let x = "world" in
print_endline x
```

Hover on first `x` variable should show "hello" or doesn't show anything instead of "world".

**Comment by db4** [comment]
Yes, in theory if the debugger currently executes the second line, hovering on the first `x` should not show anything at all (this binding does not exist anymore and may be already garbage-collected).

But I still think that OCaIDE's approach is very useful although probably not ideal. For me it's much better than nothing and makes debugging more convenient.

**Comment by hackwaly** [comment]
And the `x` variable you hover may isn't relevant with `x` variable in current frame. eg. `x` variable in another module.

There are debug console and watch pane for workaround. Though it isn't convenient than hover, but it is reasonable.

I think the most right way is going to improve ocamldebug not compromise right here.

BTW: ocamldebug has many problems. I'd like to contribute, but I'm not familiar with ocaml community. Seems they only use github as svn.

**Comment by db4** [comment]
> And the x variable you hover may isn't relevant with x variable in current frame. eg. `x` variable in another module.
> 
> There are debug console and watch pane for workaround. Though it isn't convenient than hover, but it is reasonable.
> 
> I think the most right way is going to improve ocamldebug not compromise right here.

Believe me it's really useful. If you afraid that someone is confused make it optional and off by default :)

> BTW: ocamldebug has many problems. I'd like to contribute, but I'm not familiar with ocaml community. Seems they only use github as svn.

No, github is now their primary development platform since OCaml 4.03. You can make pull requests etc. But prepare to be patient. They have limited resources and it may take months/years to push your changes into the official repo. It was me who made Windows support for ocamldebug  several years ago so I know that quite well. That's one of the reasons why I ask you for OCaIDE-style workaround that allows to work NOW.

**Comment by hackwaly** [comment]
OK, I was persuaded. It will be an option in extension configuration.
