### ISSUE TITLE
Structured data presentation in WATCH

### ISSUE THREAD

**Issue by db4** [hackwaly/vscode-ocaml#14]
I would love to see variables' data shown in a tree structure like this: https://code.visualstudio.com/Docs/editor/debugging#_data-inspection

I think we can parse pretty-printed ocaml values using the following simple rules:
1. Pair of matched parentheses of any kind (`[](){}`) denotes a new subtree
2. Delimiters (`,;`) separate tree nodes.
3. `''` and `""` denote strings that are not looked into.

IMHO, this should not be very hard to implement but will be very convenient.

**Comment by hackwaly** [comment]
Nice idea!
