### ISSUE TITLE
Can not debug with dynamic linking

### ISSUE THREAD

**Issue by huangered** [hackwaly/vscode-ocaml#16]
when i start to debug, it print the error, can you help?

```
Fatal error: cannot load shared library dllbin_prot_stubs
Reason: dlopen(dllbin_prot_stubs.so, 138): image not found
```

my environment is macos10.11.5

**Comment by hackwaly** [comment]
I'm not an OCaml expert. Did you config your opam correctly? I guess `bin_prot` package is missed in your env. Try `opam install bin_prot`.

**Comment by huangered** [comment]
thanks for you reply, find some clues https://github.com/ocaml/opam/issues/47,will close thie ticket

**Comment by qdwang** [comment]
same problem here, @huangered how did you fix this?

**Comment by huangered** [comment]
@qdwang not fix yet, but i plan to remove vscode-beta version and install new to have a try.
do you also use osx?

**Comment by qdwang** [comment]
@huangered neither Ubuntu and OSX can work the debug function and I'm using the vscode stable version. 

@hackwaly `bin_prot` has been installed, and `ocamldebug` works well in terminal. I think may be that vscode debug env cannot access the env variable `CAML_LD_LIBRARY_PATH`.

**Comment by hackwaly** [comment]
@qdwang Did you check that if simple helloworld program works (like the gif in README does)?

**Comment by qdwang** [comment]
@hackwaly not working. still the same error msg.

**Comment by hackwaly** [comment]
Can you try to use ocamldebug manually debug the bytecode?

```
ocamlc -g main.ml
ocamldebug a.out
```

```
goto 0
run
```

**Comment by qdwang** [comment]
@hackwaly Like what I said before, `ocamldebug` works just fine.

**Comment by hackwaly** [comment]
Well, I have no idea now. 

> I think may be that vscode debug env cannot access the env variable CAML_LD_LIBRARY_PATH.

I think you are right. But why I didn't encounter. I'm also macOS, and Ubuntu doesn't have separated env issues like macOS.

I suspect you didn't config opam correctly. Could you check that env variables in result of `opam config env` are in your env?

**Comment by qdwang** [comment]
Since the cmd `eval `opam config env`` lies in `~/.profile` and `~/.bashrc`, there is no doubt `ocamldebug` works in terminal.

But I don't know how to check if vscode uses a different shell or it just won't use the `.profile` and `.bashrc` config.

**Comment by hackwaly** [comment]
No, it use nodejs `child_process.spawn` to run ocamldebug. You can do a simple test to check if a  process spawned by `child_process.spawn` can find the `CAML_LD_LIBRARY_PATH` variable.

**Comment by hackwaly** [comment]
```
(* env.ml *)
print_endline (Sys.getenv "CAML_LD_LIBRARY_PATH")
```

```
// test.js
var cp = require('child_process');
var p = cp.spawn('./env');
p.stdout.pipe(process.stdout);
```

```
node test.js
```

**Comment by qdwang** [comment]
I've tried spawn the `ocamldebug` in node.js file, and it works(under my terminal). 
So the problem may be the vscode, because I didn't run vscode from my terminal? 
I don't know if this will cause the problem.

**Comment by hackwaly** [comment]
You can open devtools (command "Developer: Toggle Developer Tools") of vscode to check the `process.env. CAML_LD_LIBRARY_PATH` variable.

**Comment by qdwang** [comment]
```
process.env.CAML_LD_LIBRARY_PATH
"/home/qdwang/.opam/4.03.0/lib/stublibs"
```

This seems totally right... That's weird...

**Comment by hackwaly** [comment]
So the root problem is not `CAML_LD_LIBRARY_PATH`. Maybe you can debug vscode-ocaml extension to find some clues.

See how to debug: https://github.com/hackwaly/vscode-ocaml/issues/5#issuecomment-227983499

**Comment by qdwang** [comment]
I've cloned code, how can I build the ts file to js file?

**Comment by hackwaly** [comment]
`npm install` then press F5

**Comment by qdwang** [comment]
Why can not I use `console.log` to print in Debug Console?

**Comment by hackwaly** [comment]
You don't need `console.log`, just write the expression you like to display. Or use the watch window.
https://code.visualstudio.com/docs/extensions/debugging-extensions

**Comment by qdwang** [comment]
I've figured out that debugging with the output file of `ocamlc -g main.ml` works.

But not `corebuild -tag debug main.byte` which uses `ocamlbuild` and `ocamlfind`.

The `corebuild` output file can be debugged by `ocamldebug` in terminal.

**Comment by hackwaly** [comment]
I use ocamlbuild without this issue. `ocamlbuild -use-ocamlfind main.d.byte`

**Comment by qdwang** [comment]
corebuild is just like this

```
#!/bin/sh

ocamlbuild \
    -use-ocamlfind \
    -pkg core \
    -tag "ppx(ppx-jane -as-ppx)" \
    -tag thread \
    -tag debug \
    -tag bin_annot \
    -tag short_paths \
    -cflags "-w A-4-33-40-41-42-43-34-44" \
    -cflags -strict-sequence \
    $@

```

you can test with it and then fix the issue...

**Comment by hackwaly** [comment]
This should be fixed in new version just published.

**Comment by qdwang** [comment]
Thanks~ It's fixed.
