### ISSUE TITLE
Add "script" debug setting

### ISSUE THREAD

**Issue by db4** [hackwaly/vscode-ocaml#19]
Sometimes you need to execute several ocamldebug commands in the beginning of each debugging session (e.g. `load_printer ...` and `install_printer ...` sequence). For that ocamldebug has `source` command:

```
(ocd) help source
source: read command from file FILE.
```

You issue it after `goto 0` when ocamldebug has successfully loaded the debugee. Can you add support for that? Setting name can be `script` or `init`.

**Comment by hackwaly** [comment]
Well, you remind me that `backstep` and `start` ... commands are missing also. Though vscode's debug toolbar are limited, we can add these as special commands to editor.

ref: https://github.com/Microsoft/vscode/issues/7652

**Comment by db4** [comment]
`backstep` and `start` do not work under Windows so I don't ask for them :)

**Comment by hackwaly** [comment]
Do you also need the ability to manually run debug script while debugging?

**Comment by db4** [comment]
No. I just use script feature in Eclipse to install pretty printers/setup some parameters (e.g. `set print_depth 1000` and `set print_length 10000` to not truncate big output), so no user interaction is needed.

BTW, can you also respect `cd` option while launching the debugee? For now its working directory is not very predictable.
