### ISSUE TITLE
More debug feature wishes

### ISSUE THREAD

**Issue by db4** [hackwaly/vscode-ocaml#20]
- Support `-I` command line option ("includePath" config setting)
- Show full conversation with `ocamldebug` somewhere (debug window?). It could help to find if something goes wrong (e.g. some script commands failed, errors in debug.ts etc.). In my case I see that the following breaks debug.ts:

```
backtrace 100
#1 Timing_wrap timing_wrap.ml:17:19
#2 Create_matcher create_matcher.ml:200:108
#3 Create_matcher create_matcher.ml:150:68
(Encountered a function with no debugging information)
```

Of course, you didn't expect `(Encountered a function with no debugging information)` in a stack frame but it's not easy to find that without debugging the plugin itself.

**Comment by hackwaly** [comment]
About `-I`: You have `script` option. So you can write `directory` command in init debug script.
About show full conversation: I think it will distract users. It's better to make it as an option.

At last: We should handle "(Encountered a function with no debugging information)".

**Comment by db4** [comment]
> About `-I`: You have `script` option. So you can write `directory` command in init debug script.

Well, it makes sense.

> About show full conversation: I think it will distract users. It's better to make it as an option.

Sure. But on the other hand users would like to know if `script` commands written by themselves succeeded or not. So I think you should show the result of some of ocamldebug commands unconditionally. 

> At last: We should handle "(Encountered a function with no debugging information)".

Yes. And I must thank you for all your work. It's brilliant!

**Comment by hackwaly** [comment]
> Sure. But on the other hand users would like to know if script commands written by themselves succeeded or not. So I think you should show the result of some of ocamldebug commands unconditionally.

There is no specification about which command that ocamldebug should response what message. Most commands in script like "set xxx yyy" has no notable response. I have no idea about show what to users. Can you give a suggestion? I'm trying this, but it looks bad.

> Run script "/Users/wenyuxiang/Sandbox/debugtest/debugscript" got response ""

**Comment by db4** [comment]
- For **normal** mode the plural in 'ocamldebug commands' is overstretching a bit. Actually I only need `source` output. I think you can just capture it until `(ocd)` and dump without any modification.
- For **debug** mode you show everything that is written to/read from ocamldebug. It's enabled by some debugging flag that is normally off

**Comment by hackwaly** [comment]
> Can you give a suggestion?

I mean a text format of message shows to users when `source` command executed. 

I've tried two:

```
Run script "/Users/wenyuxiang/Sandbox/debugtest/debugscript" got response ""
```

Bad if output has long contents or multiline.

```
(ocd) source "/Users/wenyuxiang/Sandbox/debugtest/debugscript"
```

Bad if there's no output.

**Comment by db4** [comment]
For script file

```
load_printer bigarray.cma
load_printer unix.cma
set print_depth 1000
set print_length 10000
```

ocamldebug outputs

```
(ocd) source script                                                              
File C:/tools/cygwin/home/dbely/.opam/4.02.3+win32+local/lib\bigarray.cma loaded
File C:/tools/cygwin/home/dbely/.opam/4.02.3+win32+local/lib\unix.cma loaded
(ocd)                                                                            
```

Why can't you just print

```
File C:/tools/cygwin/home/dbely/.opam/4.02.3+win32+local/lib\bigarray.cma loaded
File C:/tools/cygwin/home/dbely/.opam/4.02.3+win32+local/lib\unix.cma loaded
```

If something goes wrong, say script file does not exist, user will see ocamldebug's error message:

```
Source file not found.
```

IMHO it's quite enough.
