### ISSUE TITLE
ocamldebug encoding?

### ISSUE THREAD

**Issue by db4** [hackwaly/vscode-ocaml#23]
Looks like vscode uses utf-8 for non-ASCII data (at least I see non-readable values in the watch window, while in the editor window everything is OK) . This is not always the case for ocamldebug, at least under Windows. Can we introduce `encoding` setting and decode everything from ocamldebug using that?

**Comment by hackwaly** [comment]
Did you use custom printer? I see ocamldebug will escape non-ASCII characters. I think it's better to change encoding at printer site. Because multiple printers may use different encodings (eg. utf-8 and utf-16 mixed). That case can't be handled well anyway.

I know Windows didn't use utf-8 for stdout by default. So `encoding` is still needed.

**Comment by db4** [comment]
> Did you use custom printer?

It doesn't matter.

> I see ocamldebug will escape non-ASCII characters

Yes for Linux but no for Windows. Don't ask me why :)

> I know windows didn't use utf-8 for stdout by default. So `encoding` is still needed.

Yes. And if it's missing we probably should use `files.encoding` vscode setting

**Comment by hackwaly** [comment]
> Yes. And if it's missing we probably should use files.encoding vscode setting

It's better to have a separated one. `files.encoding` is for source files. 

Try master branch. New options are "ocamldebugEncoding" (for ocamldebug) and "encoding" (for debuggee).

**Comment by db4** [comment]
Hmm, it throws exception `Unknown encoding: windows1251` in 

```
this._debuggerProc.stdout.setEncoding(args.ocamldebugEncoding || 'utf-8');
```

It's strange because I have

```
    "files.encoding": "windows1251"
```

and it works. BTW, can you handle unexpected exceptions some way? Right now if an unhanded exception occurs debugging session freezes without any message.

**Comment by hackwaly** [comment]
The exception is too early. And debug session did not established successfully. So there's no way to send some event to let client know. I didn't know what will happen if exception occurred after session established. I think vscode will do some work at that time. This remains to be seen.

Have a try.

**Comment by db4** [comment]
Now it throws `Cannot find module 'iconv-lite'`. Although I've installed iconv-lite with `npm install iconv-lite`

**Comment by hackwaly** [comment]
It's strange. Can you check that produced `.vsix` archive file (actual a zip file) contains `node_modules/iconv-lite` folder?

**Comment by db4** [comment]
It didn't. I removed `.vsix` file, rebuilt it and now the folder is there and encoding support works. Very strange.

**Comment by db4** [comment]
Although it works I would ask you to check if user-specified encoding is really exist via

```
// Check if encoding is supported 
iconv.encodingExists("us-ascii")
```

If It doesn't either use default value (utf-8? or maybe it's possible to query system locale?) of show an error message of some sort.

**Comment by hackwaly** [comment]
I wonder if "files.encoding" do similar check.
