### ISSUE TITLE
How do I pass arguments when debugging?

### ISSUE THREAD

**Issue by modlfo** [hackwaly/vscode-ocaml#3]
In the launch.json file I tried adding the "arguments" to the configuration but is seems that they are not passed to the debugged executable, like this:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "OCaml",
            "type": "ocamldebug",
            "request": "launch",
            "program": "${workspaceRoot}/main.d.byte",
            "stopOnEntry": true,
            "arguments": "file"
        }
    ]
}
```

What's the correct way of passing them?

**Comment by hackwaly** [comment]
My mistake. Your way is right!

Thanks you for point out! 
I've just uploaded a new version v0.3.1 fixed this.
