### ISSUE TITLE
Support -I command line option for ocamldebug

### ISSUE THREAD

**Issue by db4** [hackwaly/vscode-ocaml#35]
This was discussed in #20 and you convinced me that `script` option can be used instead. Unfortunately not always. Sometimes you need to use a variable value as an include directory, say `${workspaceRoot}/some/dir`. It would be easy with a configuration option in `launch.json`:

```
  "includePath": "${workspaceRoot}/some/dir",
```

but quite problematic with a script file.

**Comment by hackwaly** [comment]
I don't have a try, but I think you can use `${workspaceRoot}` in `cd` option of launch config and use relative path as include path in script file.

**Comment by db4** [comment]
Yes, but it's still not flexible enough. Include paths may use other vscode variables (not only workspaceRoot), current directory may be out of `${workspaceRoot}` etc. So I still think `-I` support would be useful (and easy to implement)

**Comment by hackwaly** [comment]
I am hesitant because there are commands other than `directory` like `load_printer` also accept filename argument. Could we treat these equally?

**Comment by db4** [comment]
I don't understand why we should care. I just propose to add an option that maps 1:1 to ocamldebug's `-I`. See https://github.com/hackwaly/vscode-ocaml/pull/36
