### ISSUE TITLE
A function list in the windows?

### ISSUE THREAD

**Issue by Enzojz** [hackwaly/vscode-ocaml#40]
Hello,

Thank for the effort. I like this plugin for vscode very much. It works smoothly on my windows.

I have a request, that have immgrated from Eclipse/OcalDE, the only thing I am missing is the fucntion list at the side of editing view(called "Outline"), where all the modules/functions are listed and just with a click I can jump anywhere I would like to.

Thank you.

best regards,
zheng

**Comment by hackwaly** [comment]
There is a symbol list for each source file. Press `Cmd + Shit + O` to see. If you mean a persistent outline view aside edit view, request VS Code please.
