### ISSUE TITLE
Syntax highlighting broken after 15 type declarations in module signature

### ISSUE THREAD

**Issue by andy-hanson** [hackwaly/vscode-ocaml#42]
Given this code:

``` ocaml
module type M = sig
    type t01
    type t02
    type t03
    type t04
    type t05
    type t06
    type t07
    type t08
    type t09
    type t10
    type t11
    type t12
    type t13
    type t14
    type t15
    type t16
    type t17
    type t18
    type t19
    type t20
end

(* A non-highlighted comment *)
```

Everything from `type t16` to the end of the file has no syntax highlighting.

**Comment by nadako** [comment]
This started for me as well since 1.4, so I had to revert to 1.3.1 for now...

**Comment by hackwaly** [comment]
Sounds like a bug of vscode.

**Comment by aeschli** [comment]
The bug is with the OCaml grammar. After every line it adds more scopes on the stacks, but never removes them. On line 20 there are already 40 scopes on the stack. (most of them of
      \* meta.type-definition.ocaml
      \* meta.type-definition-group.ocaml
 )
In VS code we now have a maximum scope stack size of 30 to prevent OOM exception.

You can use https://github.com/alexandrudima/grammar-debug to debug your grammar and see how many scopes are generated.

**Comment by hackwaly** [comment]
@aeschli Thanks!

**Comment by nadako** [comment]
I still have this problem with a really big file. You can check for yourself here: https://github.com/HaxeFoundation/haxe/blob/development/src/generators/gencommon.ml

Around line 7970 highlighting breaks...

**Comment by hackwaly** [comment]
I'll take a look when I have time.

**Comment by hackwaly** [comment]
It maybe break start at line 6509. I found the bug case:

```
module M =
struct
  let _ = fun () -> () in ()
end (* `end` is not highlighted. *)
```

The grammar can't handle this case which form like `let ... = fun ... in ...` at toplevel.

**Comment by hackwaly** [comment]
@nadako, It's fixed, and I've tested a few large files in haxe project, seems OK.

**Comment by nadako** [comment]
Thanks a lot, I'll try it out today!

**Comment by nadako** [comment]
Works, thanks!

**Comment by nadako** [comment]
Not related to this issue, but do you have an idea why "goto definition" only works within a module in that project?

**Comment by hackwaly** [comment]
You need to build `*.cmi`, `*.cmt` and `*.cmo` with bin_annot flag in build folder for ocamlmerlin to provide that function.

Well, I should document it in README.
