### ISSUE TITLE
Distributed sources

### ISSUE THREAD

**Issue by andresbh** [hackwaly/vscode-ocaml#51]
intellisence doesn't work for distributed sources, for instance if module is in another directory

**Comment by hackwaly** [comment]
Did you try this? 
https://github.com/the-lambda-church/merlin/wiki/project-configuration
https://github.com/hackwaly/vscode-ocaml/issues/42#issuecomment-239669488

**Comment by andresbh** [comment]
Cheers works like a charm for my own files. 
How does it work for general modules like Batteries?

Thanks

**Comment by hackwaly** [comment]
add a line `PKG batteries` to `.merlin`
