### ISSUE TITLE
Find references

### ISSUE THREAD

**Issue by RealyUniqueName** [hackwaly/vscode-ocaml#52]
Is there a way find all references to specified symbol?

**Comment by hackwaly** [comment]
Just place caret at symbol, vscode will highlight all occurrences. You can then press F2 to rename them.

For now cross files is not supported due to limitation of merlin.

**Comment by RealyUniqueName** [comment]
Thanks. I'm actually interested in cross files )
But if it's limitation of merling, then i guess it's not going to be implemented.

**Comment by Simn** [comment]
Could we get a normal find all references feature as well? It's strange to have rename support but not reference finding, given that it's pretty much the same thing.

**Comment by hackwaly** [comment]
@Simn First time there's no both rename support, either reference finding support. I added rename support later and missed reference finding support. Thanks for your reminder.
