### ISSUE TITLE
Cannot set breakpoints in sub module

### ISSUE THREAD

**Issue by qdwang** [hackwaly/vscode-ocaml#53]
![image](https://cloud.githubusercontent.com/assets/403616/18047204/3b46923c-6e0e-11e6-8298-cf5435419094.png)

```
+ - main.ml
+ - abc.mlpack
+ - /abc
   + - xxx.ml  
```

breakpoints in main.ml can be triggered. But not in xxx.ml

**Comment by hackwaly** [comment]
Seems doesn't work with `*.mlpack`. It works without introduce `*.mlpack`. I'll address this issue later.

**Comment by hackwaly** [comment]
I still have no idea about this. Did you get it work with ocamldebug? I didn't figure out a way to set breakpoint on one of submodule of mlpack in ocamldebug properly.

**Comment by qdwang** [comment]
```
(ocd) break @ Pass.Type 67
Loading program... done.
Breakpoint 1 at 3184384: file pass/type.ml, line 58, characters 23-24

```

This works with `ocamldebug` using `break @ [module] line`

**Comment by hackwaly** [comment]
Well, ocamldebug knows how to map modules to files, but I don't know how to map files to modules. So, previously I use a simple rule, just capitalize the filename without ext. 

This could be a challenge, and won't be solved soon. I suggest you to avoid using`mlpack` if you'd like to set breakpoints at those modules.

**Comment by qdwang** [comment]
fine

**Comment by hackwaly** [comment]
Feel free to use `mlpack`. I've fixed this bug, though not completely.

**Comment by qdwang** [comment]
So what is the limitation for now.

**Comment by hackwaly** [comment]
It doesn't work if there are more than two modules has the same filename. So, keep your module names unique can avoid issue.

**Comment by qdwang** [comment]
that is enough for me right now... thanks... you did a good job
