### ISSUE TITLE
problem matcher for OCaml

### ISSUE THREAD

**Issue by nadako** [hackwaly/vscode-ocaml#54]
I think it would make sense to have an ocaml problem matcher for build tasks. Right now, VSCode doesn't support pluggable problem matchers ([soon!](https://github.com/Microsoft/vscode/issues/492)), but you could add something like this to the README for now, and use it for implementing a proper problem matcher plugin when it becomes possible (taken from my `tasks.json` file for the Haxe project, feel free to comment and improve):

``` json
    "problemMatcher": {
        "fileLocation": "relative",
        "owner": "ocaml",
        "pattern": [
            {
                "regexp": "^File \"(.*)\", line (\\d+), characters (\\d+)-(\\d+):$",
                "file": 1,
                "line": 2,
                "column": 3,
                "endColumn": 4
            },
            {
                "regexp": "^(?:(Error|Warning)(?: \\d+)?): (.*)$",
                "severity": 1,
                "message": 2
            }
        ]
    }
```

**Comment by hackwaly** [comment]
Thank you very much! 
Actually I'm looking for some extension api to add item to this quicklist.

![c1b52a53-7f56-46a0-b00d-30cd0586b273](https://cloud.githubusercontent.com/assets/540298/18071301/50395994-6e87-11e6-8554-e52243df354e.png)

I plan to make a scaffold project example and link it in README for starter. Like your vshaxe does https://github.com/vshaxe/vshaxe#initialize-vs-code-project

**Comment by hackwaly** [comment]
I did update README to contain a tips section that cover `tasks.json`. 

After some thoughts, I dropped the plan to add project generator in extension. Because ocaml has so many build systems, users may prefer any one of them. Maybe write a yeoman generator is a good idea.

**Comment by db4** [comment]
By the way, the problem parser above doesn't correctly parse error messages like this:

```
File "test.ml", line 1, characters 14-15:                                 
Error: This expression has type int but an expression was expected of type
         float
```

Third line is discarded and the error message truncated to `This expression has type int but an expression was expected of type`. Does anyone know how to do it correctly if at all possible?

**Comment by hackwaly** [comment]
Seems not possible for now. I tried that replace `.` with `[\s\S]`, and it doesn't work. So I think VS Code process the patterns line by line.

Hope there will be an programable problem matcher api on VS Code.

**Comment by db4** [comment]
Looks like I've finally found the working solution:

```
                    "pattern": [
                        {
                            "regexp": "^File \"(.*)\", line (\\d+), characters (\\d+)-(\\d+):$",
                            "file": 1,
                            "line": 2,
                            "column": 3,
                            "endColumn": 4
                        },
                        {
                            "regexp": "^(?:(?:Parse\\s+)?(Warning|[Ee]rror)(?:\\s+\\d+)?:)?\\s+(.*)$",
                            "severity": 1,
                            "message": 2,
                            "loop": true
                        }
                    ]
```

I tried

```
                    "pattern": [
                        {
                            "regexp": "^File \"(.*)\", line (\\d+), characters (\\d+)-(\\d+):$",
                            "file": 1,
                            "line": 2,
                            "column": 3,
                            "endColumn": 4
                        },
                        {
                            "regexp": "^(?:Parse\\s+)?(Warning|[Ee]rror)(?:\\s+\\d+)?:\\s+(.*)$",
                            "severity": 1,
                            "message": 2
                        },
                        {
                            "regexp": "^\\s+(.*)$",
                            "message": 1,
                            "loop": true
                        }
                    ]
```

but surprisingly it does not work as expected.

**Comment by hackwaly** [comment]
@db4 Thanks for your hard working!

**Comment by db4** [comment]
BTW, there is another issue with OCaml problem matchers: https://github.com/Microsoft/vscode/issues/7918
I hope they will finally resolve it some day

**Comment by db4** [comment]
Updated problem matcher (the previous one failed to parse `The implementation ... does not match the interface ...` compiler messages that did not contain column fields):

```
"pattern": [
    {
        "regexp": "^File \"(.*)\", line (\\d+)(?:, characters (\\d+)-(\\d+))?:$",
        "file": 1,
        "line": 2,
        "column": 3,
        "endColumn": 4
    },
    {
        "regexp": "^(?:(?:Parse\\s+)?(Warning|[Ee]rror)(?:\\s+\\d+)?:)?\\s+(.*)$",
        "severity": 1,
        "message": 2,
        "loop": true
    }
]
```

**Comment by hackwaly** [comment]
@db4 , README updated.

**Comment by hackwaly** [comment]
Problem matcher `ocamlc`  is added. https://github.com/hackwaly/vscode-ocaml/commit/be23924c9be8d7ea1db13a2e8ced8559313cd7c7
