### ISSUE TITLE
Add a command to switch between module implementation/signature (.ml/.mli files)

### ISSUE THREAD

**Issue by db4** [hackwaly/vscode-ocaml#58]
I think it can be quite useful. In case the corresponding file does not exist we can just create a new one.

**Comment by hackwaly** [comment]
Good idea!

**Comment by db4** [comment]
Tried to use this, got:
![image](https://cloud.githubusercontent.com/assets/6112699/18623747/9ec38324-7e49-11e6-82c1-ca7b2c77c058.png)
What log should I look into?

**Comment by hackwaly** [comment]
My mistake, will fix soon.

**Comment by db4** [comment]
Yes, now it works. Thank you!
