### ISSUE TITLE
Abnormal termination of ocamldebug

### ISSUE THREAD

**Issue by db4** [hackwaly/vscode-ocaml#66]
If ocamldebug lose TCP connection to debugee it can die with `Uncaught exception: Sys_error("Invalid argument")`. It may be classified as ocamldebug's own bug or as wrong client behavior but stll: can we gracefully handle such situation?  Right now the plugin waits for `Program exit.` or `Program end.` forever and requires additional click on Stop (Shift+F5) to close the debug session. Can you check that ocamldebug process has already exited and then send TerminatedEvent()?

**Comment by hackwaly** [comment]
I don't know if ocamldebug will exit after it output `Uncaught exception: Sys_error("Invalid argument")`. I can add a logic - when it did exit, close the debug session. Can we stop the session safely when any `Uncaught exception` encountered?

**Comment by db4** [comment]
I would monitor if the ocamldebug process still exist. Is it possible with Node.js?

**Comment by db4** [comment]
Great, now the debug session is terminated correctly. Thanks!
