### ISSUE TITLE
Problem markers

### ISSUE THREAD

**Issue by db4** [hackwaly/vscode-ocaml#68]
Problem markers from merlin and OCaml compiler currently go to the same `Problems` view. Is it possible to separate them from each other like `Output` view where you can select Extensions, Git, or Tasks output? And after `Run Build Task` one would like to activate `Build` markers automatically. Can you also add `Clear` button like `Output` view has?

**Comment by hackwaly** [comment]
Where is the `Problems` view, I can't even find it. Could you please give a snapshot? I think this is missing from vscode.

**Comment by db4** [comment]
You can open it with View->Problems (Ctrl+Shift+M). It is where merlin/build errors/warnings go.

**Comment by hackwaly** [comment]
I think it can't be separated for now. I didn't see any api or ui for it. You can make a feature request to vscode.

**Comment by db4** [comment]
I see. And also no way to clear it before build?

**Comment by hackwaly** [comment]
I can use some api to clear problems produced by linter (merlin), but no way to clear the problems produced by build task.

**Comment by db4** [comment]
> I can use some api to clear problems produced by linter (merlin)

IMHO it would be useful. After the build you probably would like to see the build problems only.

**Comment by hackwaly** [comment]
But there's no api (event or callback) to know if build started or finished.

**Comment by db4** [comment]
Can you detect that the build task is going to start and then clear problems view?

And right now you can set the source of the problem (see screenshot in https://github.com/Microsoft/vscode/issues/12675). It will allow to use filters.
