### ISSUE TITLE
Location of ocp-indent configuration file

### ISSUE THREAD

**Issue by modlfo** [hackwaly/vscode-ocaml#72]
Hi, is it possible to specify the location of the ocp-indent configuration file?

I have a custom configuration in my workspace and seems like ocp-indent ignores it and uses the default indentation (I'm using windows). Is it possible to specify the location of the file that should be used?

Thanks!

**Comment by hackwaly** [comment]
Now your `.ocp-indent` should work.

**Comment by modlfo** [comment]
It does! Thank you very much!
