### ISSUE TITLE
any option to disable error hints

### ISSUE THREAD

**Issue by bobzhang** [hackwaly/vscode-ocaml#73]
I like that merlin  can give me some hints of auto completion. 
But one thing very distracting is the false alarm (maybe due to my bad configuration), I used to run build in  a watch mode which gives me a much more reliable error check (and it's just so fast and reliable).
my question is is there any option to turn off those error hints?

**Comment by hackwaly** [comment]
There are `ocaml.lintOnChange` and `ocaml.lintOnSave` can control the lint triggers. You can set them all to false to disable linter.
