### ISSUE TITLE
Debugger: retrieveSource() problem

### ISSUE THREAD

**Issue by db4** [hackwaly/vscode-ocaml#76]
When I step into a function from another file, I see the following:
![image](https://cloud.githubusercontent.com/assets/6112699/21000771/b218beee-bd2d-11e6-95d4-a4b774ce4d46.png)
(note `$1`)
This is introduced by 
```typescript
 // FIXME: make sure do not accidently replace "<|a|>" in a string or comment.
return line.replace(/^\d+ /, '').replace(/<\|[ab]\|>/, '$1');
```
in `debug.ts`. What is the purpose of `$1`? Why not just replace it with an empty string?

**Comment by hackwaly** [comment]
Sorry for the late response.
