### ISSUE TITLE
Preview of the declaration

### ISSUE THREAD

**Issue by db4** [hackwaly/vscode-ocaml#8]
VSCode editor is expected to provide "preview of the declaration" functionality on Ctrl+hover:
https://code.visualstudio.com/Docs/editor/editingevolved#_go-to-definition. I think you should show the value declaration from .mli file if available (now the value definition from .ml has a priority)

**Comment by hackwaly** [comment]
Since vscode doesn't support goto multiple definitions via quickpick. I arbitrarily choose .ml over .mli in my flavor. 

In my opinion, most cases people want goto implementation site not declaration site. If I'm wrong, I'll add a config option to extension.

**Comment by hackwaly** [comment]
Eh. I'm wrong! VS Code seems do provide support goto multiple definitions via quickpick. I'll take a try.

**Comment by hackwaly** [comment]
Fixed in 0.4.3
