### ISSUE TITLE
utop-related options

### ISSUE THREAD

**Issue by db4** [hackwaly/vscode-ocaml#82]
The following options IMHO would be convenient:
- make toplevel command configurable and set to "ocaml" by default (not everyone has utop installed)
- optionally attach ";;" to a text sent to the terminal window. Is it possible to analyze the selected text and find out if it ends with ";;"?

**Comment by db4** [comment]
This code
```javascript
            utopTerm = vscode.window.createTerminal('OCaml UTop');
            utopTerm.sendText('utop', true);
            utopTerm.show();
```
worked under Windows, but this one from b09e104abac08bde6c2dec2428dd414d180d8d08
```javascript
            replTerm = vscode.window.createTerminal('OCaml REPL', configuration.get<string>('replPath', 'ocaml'));
            replTerm.show();
```
unfortunately doesn't (this variant of `createTerminal()` needs `ocaml.exe` otherwise it cannot launch the toplevel). Maybe change `replPath` default value to `ocaml.exe` or rollback to the previous method of creating the terminal?

**Comment by db4** [comment]
And a related question. Changing workspace/user preference `ocaml.replPath` does not affect the current vscode session: I need to restart it to take effect. Is it expected behavior?

**Comment by hackwaly** [comment]
No, it looks like an issue of vscode.
