### ISSUE TITLE
Syntax highlighting regression in 0.6.18

### ISSUE THREAD

**Issue by elfmimi** [hackwaly/vscode-ocaml#84]
Wrong : 0.6.18
![0 6 18 wrong](https://cloud.githubusercontent.com/assets/2020873/24357088/67ec8bba-1337-11e7-89d1-d9822763b64a.png)

Correct : 0.6.16
![0 6 16 correct](https://cloud.githubusercontent.com/assets/2020873/24357087/67e0215e-1337-11e7-826b-fb3c81082b35.png)

**Comment by hackwaly** [comment]
Sorry, my mistake. Lack of auto tests.

**Comment by elfmimi** [comment]
Thanks a lot!

> Lack of auto tests.

true
