### ISSUE TITLE
Add Keybinding for commands

### ISSUE THREAD

**Issue by GiBg1aN** [hackwaly/vscode-ocaml#85]
It would be great if you could implement a keybind option for **Ctrl+shift+P** commands, for instance F# Ionide plugin has a **Alt+Enter** keybind for "Send selection to Interactive", could you please add  a keybind option for that command, thank you in advance.

**Comment by hackwaly** [comment]
You can add keybinding yourself by edit `keybindings.json`. This way give you most flexibility while doesn't force all users to use ALT+Enter as shortcut key. We also have "Send selection as statement to REPL" command will auto terminate selection with ";;", you can bind as you like.

**Comment by GiBg1aN** [comment]
Ok, thank you!
