### ISSUE TITLE
Utop support

### ISSUE THREAD

**Issue by davidmartos96** [hackwaly/vscode-ocaml#86]
Hello, I was wondering how does one use the utop integration from Visual Studio. I don't seem to find any option related with utop in the settings. Sorry for the inconvinience, I am fairly new with Visual Studio

**Comment by hackwaly** [comment]
By changing the `ocaml.replPath.unix` to `utop`. If it doesn't in PATH env, use full path instead. Use `ocaml.replPath.windows` If you are on Windows OS.

Sorry, for the inconvenience. I'll tune the config doc.
