### ISSUE TITLE
Format selection

### ISSUE THREAD

**Issue by db4** [hackwaly/vscode-ocaml#9]
Format code (Shift+Alt+F) seems to work only for the whole file and does nothing then some text is selected. Is it possible to format the selection in that case?

**Comment by hackwaly** [comment]
No, this is not implemented. This could be easily added. Note it does not code format, it do indent only.

BTW. Could you tell me which situation you do want to format selection only?

**Comment by db4** [comment]
Well, I have a big .ml file which I add some new code to. I don't like to reformat everything because existing indentation changes and makes commit diffs unclear. And I get used to use this feature since OcaIDE :)

**Comment by hackwaly** [comment]
Fixed in 0.4.3

**Comment by AllanWang** [comment]
@hackwaly is there any setup required to enable this? formatting doesn't seem to do anything for me

**Comment by hackwaly** [comment]
install ocp-indent first.

**Comment by AllanWang** [comment]
@hackwaly I do have it installed. I'm on windows though so it is under C:/Ocaml/... vs C:/[user]...

**Comment by AllanWang** [comment]
I've also set `ocaml.ocpIndentPath` to point to `ocp-indent.exe`

**Comment by hackwaly** [comment]
That's  strange! Try debug this extension to figure out what's wrong.
