### ISSUE TITLE
The send to repl options have disappeared from the list of available shortcuts

### ISSUE THREAD

**Issue by thewickedaxe** [hackwaly/vscode-ocaml#90]
**VS code details**
Version 1.11.2
Commit 6eaebe3b9c70406d67c97779468c324a7a95db0e
Date 2017-04-13T08:01:14.464Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

** Ocaml Plugin details **
Version: 0.6.26

I used to rely a lot on the send to utop/repl command that we were allowed to define. The command appears to have disappeared from the list of available commands.

ocp-indent and merlin were installed fine and ocaml version is 4.04.0 on Ubuntu 16.04

**Comment by hackwaly** [comment]
Sorry for the late response. I'll fix it soon.

**Comment by hackwaly** [comment]
Please check if it is fixed.

**Comment by thewickedaxe** [comment]
Actually this is still not fixed and I have the latest version

**Comment by hackwaly** [comment]
I'm sorry but I didn't reproduce your problem.

Could you please provide a screenshot to describe what problem you faced?

**Comment by thewickedaxe** [comment]
I'm attaching 2 images below. I have ocp-indent and merlin installed. The options that the plugin provides in settings.json seem to be fine. But the options in keybindings.json don't appear to get added.

![nooptions](https://cloud.githubusercontent.com/assets/6086877/25776816/6c8a448a-3297-11e7-821d-e6c614ab8b73.png)
![packages](https://cloud.githubusercontent.com/assets/6086877/25776817/6c9adac0-3297-11e7-82b0-4075656f6340.png)

**Comment by hackwaly** [comment]
OCaml extension is lazy loaded when you open an OCaml project. Please make sure you have loaded OCaml extension (eg. open an OCaml file in vscode) before you config the keybindings.

**Comment by thewickedaxe** [comment]
I see. Got it. It works now. Thanks!!
