### ISSUE TITLE
merlin and ocp-indent doesn't work with ArchLinux

### ISSUE THREAD

**Issue by svenhsia** [hackwaly/vscode-ocaml#91]
Hi, 

Thank you for this magnific plugin of vscode.

But I didn't manage to run it properly on my laptop with Archlinux installed.

I thought it was the problem of path settings, so I followed your instrcutions and add these lines as follow in the setting.json: 

`"files.associations": {
        "*.ml": "ocaml",
        "*.mli": "ocaml"
    },
    "ocaml.ocpIndentPath": "/home/sven/.opam/system/share/ocp-indent/",
    "ocaml.merlinPath": "/home/sven/.opam/system/share/merlin/",`

However, neither of these two functionnalities works.
Would you please give me some advices?
多谢！

PS: merlin works with utop.

**Comment by hackwaly** [comment]
你可以不用配置ocpIndentPath和merlinPath，只要merlin和ocp-indent在你的$PATH里就行（也就是配置好opam就可以了）。这两个参数需要指向的是可执行文件，而不是目录。
