### ISSUE TITLE
Keep a list of previous jumps and allow to jump back

### ISSUE THREAD

**Issue by Khady** [hackwaly/vscode-ocaml#94]
This is a feature request.

In merlin mode for emacs, there a function `merlin-pop-stack` or `C-c &`. Each time you do a jump using merlin, (`go to definition`, `go to implementation`, `jump to enclosing fun, let, module or match`, ...), it is possible to jump back using `merlin-pop-stack`. It is very convenient, because you can move your cursor, do some modifications and still you are able to jump back where you were. Much more powerful than `cursorUndo` or `workbench.action.navigateback` in vscode because it takes only the jumps into account and not all the cursor movements.

I don't know anything about vscode extensions, so it's hard for me to contribute. But let me know if I can help.

**Comment by hackwaly** [comment]
Vscode already has this feature.

**Comment by Khady** [comment]
Can you tell me which command it is then? Alt+ctrl+- isn't the answer. Cursorundo either.

**Comment by hackwaly** [comment]
On my mac it's "ctrl+-".

**Comment by Khady** [comment]
Ok. It's `Alt+ctrl+-` on my linux, and the command name is `workbench.action.navigateback`. But unfortunatly, like `cursorUndo`, this command takes into account the movements of the cursor, not only the jumps. So if I jump to a function definition, then move my cursor 3 times down, and do `workbench.action.navigateback`, the cursor will move one time up. I would like the cursor to jump back to the function definition, and then on the function call.

**Comment by hackwaly** [comment]
This feature should be requested to https://github.com/Microsoft/vscode/issues. I use emacs rarely, and I do jump back in vscode by press `ctrl+-` many times. I didn't feel it's inconvenience yet.

**Comment by Khady** [comment]
Ok, I will ask there then. FTR, in emacs this is part of the merlin mode and not a feature that exists in emacs by itself. And by leaving this feature to the editor, I'm not sure it would support to go back after a `jump to enclosing fun, let, module or match` for example, as it's not an existing `go to` command. But I don't know vscode internals, so it's just a guess.

**Comment by Khady** [comment]
Here is the corresponding feature request: https://github.com/Microsoft/vscode/issues/27112

Thanks for your quick answer and your work on this extension!
